# Strictly for local development

# Use root/example as user/password credentials
version: '3.1'

services:
  # Connect using:
  #
  # mysql --host=0.0.0.0 --user=root --password=example
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ticket_api_local
    ports:
      - 3306:3306
      - 33060:33060
